apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    tags.datadoghq.com/env: "dev-auto-inject"
    tags.datadoghq.com/service: "cartservice"
    tags.datadoghq.com/version: "0.5.0"
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
        tags.datadoghq.com/env: "dev-auto-inject"
        tags.datadoghq.com/service: "cartservice"
        tags.datadoghq.com/version: "0.5.0"
        admission.datadoghq.com/enabled: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
          image: cartservice
          ports:
            - containerPort: 7070
          env:
            - name: REDIS_ADDR
              value: "redis-cart:6379"
            # LAB: Uncomment to simulate latency (in milliseconds) for Datadog APM testing
            - name: SIMULATE_LATENCY_MS
              value: "2000"  # 2 seconds delay
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_EXECUTION_TRACE_ENABLED
              value: "true"
            - name: DD_GIT_REPOSITORY_URL
              value: "github.com/mujokodatadog/microservices-demo-multiarch"
            - name: DD_GIT_COMMIT_SHA
              value: "{{.GIT_COMMIT_SHA}}"
            - name: DD_GIT_BRANCH
              value: "{{.GIT_BRANCH}}"
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070